# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f615fdee225eacb1cdbcd68405203a931911bab0c34e14b52ebfb41c2a2d9092e281f5fda22261ee8e490b6ce454870053d088da0c3d694bc63984d434897e95

test:
  secret_key_base: cc9874d7b4be2d485b773fedd1276c8de2276071582f14e37160127369135a76c14fe79df88ebbf9ac2dd58be7754cf6b0a5ea40469818dbb47dd65b2964fb9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
